// ============================================================
// MOCK LISTING DATA — REPLACE WITH LIVE NORTHWEST MLS IDX FEED
// ============================================================
// This is the SINGLE source of listing data for the Properties section.
// Every card, filter, map pin, and detail page reads from LISTINGS below.
// To go live: swap this file's export for data pulled from your approved
// NWMLS IDX provider. Keep the same field names so nothing downstream
// (cards, filters, detail pages, map) needs to change.
// See PROPERTIES-SETUP.md for provider options, credentials, and steps.

// Filter the live feed to these Listing Agent IDs (LAG):
export const AGENTS = {
  jack: { name: 'Jack Macdonald', lag: '136199' },
  stephen: { name: 'Stephen Macdonald', lag: '65120' }
  // Add other team member LAG IDs here as needed.
};

export const LISTINGS = [
  { id: 'l1', slug: 'bellevue/1420-lakeview-way', status: 'active', featured: true, price: 2450000, address: '1420 Lakeview Way NE', city: 'Bellevue', neighborhood: 'Meydenbauer', beds: 5, baths: 4.5, sqft: 4200, lotSizeSqft: 12000, propertyType: 'Single Family', yearBuilt: 2019, garageSpaces: 3, daysOnMarket: 6, waterfront: false, views: true, newConstruction: false, openHouse: { date: 'Sat, Aug 8', time: '1:00–3:00 PM' }, agentLAG: '136199', agentName: 'Jack Macdonald', mapX: 62, mapY: 35, taxesAnnual: 21400, description: 'A refined Meydenbauer estate with soaring ceilings, a chef\u2019s kitchen, and westward lake and mountain views from nearly every principal room.', features: ['Chef\u2019s kitchen with Wolf/Sub-Zero appliances', 'Primary suite with private deck', 'Home theater and wine cellar', 'Smart home automation throughout'] },
  { id: 'l2', slug: 'kirkland/88-lake-washington-blvd', status: 'active', featured: false, price: 3150000, address: '88 Lake Washington Blvd', city: 'Kirkland', neighborhood: 'Houghton', beds: 4, baths: 3, sqft: 3400, lotSizeSqft: 8000, propertyType: 'Single Family', yearBuilt: 2015, garageSpaces: 2, daysOnMarket: 14, waterfront: true, views: true, newConstruction: false, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 55, mapY: 20, taxesAnnual: 26200, description: 'True Lake Washington waterfront with a private dock, walls of glass, and direct beach access just minutes from downtown Kirkland.', features: ['Private dock and moorage', 'Walls of glass facing the lake', 'Radiant floor heating', 'Heated driveway'] },
  { id: 'l3', slug: 'redmond/1502-nw-9th-st', status: 'active', featured: false, price: 895000, address: '1502 NW 9th St', city: 'Redmond', neighborhood: 'Downtown Redmond', beds: 3, baths: 2.5, sqft: 1900, lotSizeSqft: 1200, propertyType: 'Townhome', yearBuilt: 2021, garageSpaces: 2, daysOnMarket: 21, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '136199', agentName: 'Jack Macdonald', mapX: 70, mapY: 30, taxesAnnual: 7100, description: 'A low-maintenance modern townhome steps from downtown Redmond\u2019s shops, restaurants, and the Eastrail trail.', features: ['Rooftop deck', 'Attached 2-car garage', 'Quartz countertops throughout', 'EV charging pre-wired'] },
  { id: 'l4', slug: 'issaquah/2210-newport-way', status: 'active', featured: false, price: 1150000, address: '2210 Newport Way SW', city: 'Issaquah', neighborhood: 'Squak Mountain', beds: 4, baths: 3, sqft: 2800, lotSizeSqft: 7500, propertyType: 'Single Family', yearBuilt: 2008, garageSpaces: 2, daysOnMarket: 30, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 40, mapY: 68, taxesAnnual: 9800, description: 'A well-kept family home on a quiet cul-de-sac with easy access to Issaquah\u2019s top-rated schools and trailheads.', features: ['Bonus room / home office', 'Fully fenced backyard', 'Updated kitchen (2021)', 'Three-car driveway'] },
  { id: 'l5', slug: 'sammamish/24800-se-32nd-pl', status: 'active', featured: true, price: 2050000, address: '24800 SE 32nd Pl', city: 'Sammamish', neighborhood: 'Trossachs', beds: 5, baths: 4, sqft: 3900, lotSizeSqft: 15000, propertyType: 'Single Family', yearBuilt: 2022, garageSpaces: 3, daysOnMarket: 4, waterfront: false, views: true, newConstruction: true, openHouse: { date: 'Sun, Aug 9', time: '12:00–2:00 PM' }, agentLAG: '136199', agentName: 'Jack Macdonald', mapX: 78, mapY: 55, taxesAnnual: 17200, description: 'A newly built Trossachs estate with plateau views, a designer kitchen, and a resort-style backyard.', features: ['Never-lived-in construction', 'Covered outdoor kitchen', 'Vaulted great room', 'Owned solar array'] },
  { id: 'l6', slug: 'bothell/17800-102nd-ave', status: 'active', featured: false, price: 585000, address: '17800 102nd Ave NE #204', city: 'Bothell', neighborhood: 'Canyon Park', beds: 2, baths: 2, sqft: 1250, lotSizeSqft: 0, propertyType: 'Condo', yearBuilt: 2018, garageSpaces: 1, daysOnMarket: 45, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 45, mapY: 12, taxesAnnual: 4600, description: 'A bright, low-maintenance condo minutes from I-405 with a private balcony and secure garage parking.', features: ['In-unit washer/dryer', 'Private balcony', 'Secure covered parking', 'Community fitness center'] },
  { id: 'l7', slug: 'bellevue/9910-se-24th-st', status: 'coming_soon', featured: false, price: 2200000, address: '9910 SE 24th St', city: 'Bellevue', neighborhood: 'Enatai', beds: 4, baths: 3.5, sqft: 3600, lotSizeSqft: 9000, propertyType: 'Single Family', yearBuilt: 2020, garageSpaces: 3, daysOnMarket: 0, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '136199', agentName: 'Jack Macdonald', mapX: 65, mapY: 42, taxesAnnual: 18900, description: 'Coming soon in Enatai — a contemporary build with an open-concept main floor and a flat, sun-drenched backyard.', features: ['Main-floor primary suite', 'Chef\u2019s pantry', 'Heated three-car garage', 'Landscaped, flat lot'] },
  { id: 'l8', slug: 'kirkland/455-market-st', status: 'coming_soon', featured: false, price: 1050000, address: '455 Market St', city: 'Kirkland', neighborhood: 'Downtown Kirkland', beds: 3, baths: 2.5, sqft: 2100, lotSizeSqft: 1500, propertyType: 'Townhome', yearBuilt: 2023, garageSpaces: 2, daysOnMarket: 0, waterfront: false, views: true, newConstruction: true, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 52, mapY: 22, taxesAnnual: 8400, description: 'A new-construction townhome coming soon, walkable to Kirkland\u2019s waterfront, restaurants, and marina.', features: ['Rooftop deck with lake glimpses', 'Never-lived-in', 'Attached garage', 'High-end finishes throughout'] },
  { id: 'l9', slug: 'redmond/8811-166th-ave', status: 'pending', featured: false, price: 1320000, address: '8811 166th Ave NE', city: 'Redmond', neighborhood: 'Education Hill', beds: 4, baths: 3, sqft: 2600, lotSizeSqft: 6000, propertyType: 'Single Family', yearBuilt: 2012, garageSpaces: 2, daysOnMarket: 18, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '136199', agentName: 'Jack Macdonald', mapX: 72, mapY: 25, taxesAnnual: 11400, description: 'Under contract — a light-filled Education Hill home close to top-rated schools and the Microsoft campus.', features: ['Open kitchen/great room', 'Finished basement rec room', 'Covered patio', 'Two-car garage'] },
  { id: 'l10', slug: 'sammamish/2100-228th-ave', status: 'pending', featured: false, price: 1875000, address: '2100 228th Ave SE', city: 'Sammamish', neighborhood: 'Klahanie', beds: 5, baths: 3.5, sqft: 3800, lotSizeSqft: 13000, propertyType: 'Single Family', yearBuilt: 2016, garageSpaces: 3, daysOnMarket: 25, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 80, mapY: 58, taxesAnnual: 15600, description: 'Under contract in Klahanie — a spacious family home backing to greenbelt with a resort-style pool.', features: ['In-ground pool', 'Backs to greenbelt', 'Bonus/media room', 'Three-car garage'] },
  { id: 'l11', slug: 'bellevue/633-108th-ave', status: 'sold', featured: false, price: 2010000, address: '633 108th Ave NE', city: 'Bellevue', neighborhood: 'Downtown Bellevue', beds: 4, baths: 3, sqft: 3100, lotSizeSqft: 8500, propertyType: 'Single Family', yearBuilt: 2017, garageSpaces: 2, daysOnMarket: 12, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '136199', agentName: 'Jack Macdonald', mapX: 60, mapY: 40, taxesAnnual: 16200, description: 'Sold by the Macdonald Group — a downtown Bellevue home that closed above list price after multiple offers.', features: ['Walk to Bellevue Square', 'Updated kitchen', 'Fenced yard', 'Two-car garage'] },
  { id: 'l12', slug: 'kirkland/210-3rd-ave', status: 'sold', featured: false, price: 720000, address: '210 3rd Ave S #302', city: 'Kirkland', neighborhood: 'Downtown Kirkland', beds: 2, baths: 2, sqft: 1400, lotSizeSqft: 0, propertyType: 'Condo', yearBuilt: 2019, garageSpaces: 1, daysOnMarket: 9, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 53, mapY: 18, taxesAnnual: 5900, description: 'Sold by the Macdonald Group — a downtown Kirkland condo that closed in under two weeks.', features: ['Walk Score 95', 'In-unit laundry', 'Covered parking', 'Building rooftop deck'] },
  { id: 'l13', slug: 'issaquah/615-front-st', status: 'sold', featured: false, price: 980000, address: '615 Front St S', city: 'Issaquah', neighborhood: 'Olde Town', beds: 3, baths: 2, sqft: 2200, lotSizeSqft: 6500, propertyType: 'Single Family', yearBuilt: 2005, garageSpaces: 2, daysOnMarket: 20, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '136199', agentName: 'Jack Macdonald', mapX: 38, mapY: 70, taxesAnnual: 8100, description: 'Sold by the Macdonald Group — a classic Olde Town Issaquah home, walkable to the historic downtown core.', features: ['Covered front porch', 'Detached workshop', 'Mature landscaping', 'Updated systems'] },
  { id: 'l14', slug: 'bothell/17020-riverside-dr', status: 'active', featured: true, price: 2650000, address: '17020 Riverside Dr', city: 'Bothell', neighborhood: 'North Creek', beds: 4, baths: 3, sqft: 3300, lotSizeSqft: 11000, propertyType: 'Single Family', yearBuilt: 2014, garageSpaces: 3, daysOnMarket: 8, waterfront: true, views: true, newConstruction: false, openHouse: { date: 'Sat, Aug 8', time: '11:00 AM–1:00 PM' }, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 48, mapY: 8, taxesAnnual: 19800, description: 'A riverfront retreat on the Sammamish River with a private dock, expansive decking, and forest privacy.', features: ['Private river dock', 'Wraparound deck', 'Vaulted great room', 'Whole-home generator'] },

  // ---- Live NWMLS listings, added manually while the IDX widget is connected ----
  // Fields not shown on the source listing page (lot size, year built, garage,
  // days on market, taxes) are left null and render as "—" / "N/A" until the
  // real feed supplies them.
  { id: 'l15', slug: 'bellevue/4651-171st-ave-se', status: 'active', featured: true, price: 2499950, address: '4651 171st Avenue SE', city: 'Bellevue', neighborhood: null, beds: 4, baths: 4, sqft: 3710, lotSizeSqft: null, propertyType: 'Single Family', yearBuilt: null, garageSpaces: null, daysOnMarket: null, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 66, mapY: 45, taxesAnnual: null, description: 'A 4-bedroom, 4-bath home in Bellevue, WA, offered through NWMLS and Compass.', features: ['Provided by NWMLS, Compass'] },
  { id: 'l16', slug: 'issaquah/7511-271st-ave-se-unit-c', status: 'active', featured: false, price: 2350000, address: '7511 271st Avenue SE, Unit C', city: 'Issaquah', neighborhood: null, beds: 4, baths: 5, sqft: 4732, lotSizeSqft: null, propertyType: 'Single Family', yearBuilt: null, garageSpaces: null, daysOnMarket: null, waterfront: false, views: false, newConstruction: true, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 40, mapY: 66, taxesAnnual: null, description: 'A 4-bedroom, 5-bath new-construction home in Issaquah, WA, offered through NWMLS and Compass.', features: ['Provided by NWMLS, Compass'] },
  { id: 'l17', slug: 'seattle/2112-n-64th-street', status: 'active', featured: false, price: 2250000, address: '2112 N 64th Street', city: 'Seattle', neighborhood: null, beds: 4, baths: 4, sqft: 3110, lotSizeSqft: null, propertyType: 'Single Family', yearBuilt: null, garageSpaces: null, daysOnMarket: null, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 22, mapY: 40, taxesAnnual: null, description: 'A 4-bedroom, 4-bath home in Seattle, WA, offered through NWMLS and Compass.', features: ['Provided by NWMLS, Compass'] },
  { id: 'l18', slug: 'bainbridge-island/4089-rockaway-beach-rd-ne', status: 'active', featured: false, price: 1850000, address: '4089 Rockaway Beach Road NE', city: 'Bainbridge Island', neighborhood: null, beds: 4, baths: 4, sqft: 3147, lotSizeSqft: null, propertyType: 'Single Family', yearBuilt: null, garageSpaces: null, daysOnMarket: null, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 6, mapY: 48, taxesAnnual: null, description: 'A 4-bedroom, 4-bath home on Bainbridge Island, WA, offered through NWMLS and Compass.', features: ['Provided by NWMLS, Compass'] },
  { id: 'l19', slug: 'renton/10667-se-170th-pl', status: 'active', featured: false, price: 1199800, address: '10667 SE 170th Place', city: 'Renton', neighborhood: null, beds: 5, baths: 3, sqft: 3304, lotSizeSqft: null, propertyType: 'Single Family', yearBuilt: null, garageSpaces: null, daysOnMarket: null, waterfront: false, views: false, newConstruction: true, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 58, mapY: 82, taxesAnnual: null, description: 'A 5-bedroom, 3-bath new-construction home in Renton, WA, offered through NWMLS and Compass.', features: ['Provided by NWMLS, Compass'] },
  { id: 'l20', slug: 'renton/10668-se-170th-pl', status: 'active', featured: false, price: 1189800, address: '10668 SE 170th Place', city: 'Renton', neighborhood: null, beds: 4, baths: 3, sqft: 3110, lotSizeSqft: null, propertyType: 'Single Family', yearBuilt: null, garageSpaces: null, daysOnMarket: null, waterfront: false, views: false, newConstruction: true, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 60, mapY: 82, taxesAnnual: null, description: 'A 4-bedroom, 3-bath new-construction home in Renton, WA, offered through NWMLS and Compass.', features: ['Provided by NWMLS, Compass'] },
  { id: 'l21', slug: 'kirkland/12625-ne-133rd-pl', status: 'pending', featured: false, price: 1295000, address: '12625 NE 133rd Place', city: 'Kirkland', neighborhood: null, beds: 4, baths: 3, sqft: 2140, lotSizeSqft: null, propertyType: 'Single Family', yearBuilt: null, garageSpaces: null, daysOnMarket: null, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 34, mapY: 22, taxesAnnual: null, description: 'A 4-bedroom, 3-bath home in Kirkland, WA, offered through NWMLS and Compass.', features: ['Provided by NWMLS, Compass'] },
  { id: 'l22', slug: 'renton/10675-se-170th-pl', status: 'pending', featured: false, price: 1149800, address: '10675 SE 170th Place', city: 'Renton', neighborhood: null, beds: 4, baths: 3, sqft: 3110, lotSizeSqft: null, propertyType: 'Single Family', yearBuilt: null, garageSpaces: null, daysOnMarket: null, waterfront: false, views: false, newConstruction: true, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 59, mapY: 83, taxesAnnual: null, description: 'A 4-bedroom, 3-bath new-construction home in Renton, WA, offered through NWMLS and Compass.', features: ['Provided by NWMLS, Compass'] },
  { id: 'l23', slug: 'bothell/9220-ne-191st-st', status: 'pending', featured: false, price: 695000, address: '9220 NE 191st Street', city: 'Bothell', neighborhood: null, beds: 3, baths: 2, sqft: 1218, lotSizeSqft: null, propertyType: 'Single Family', yearBuilt: null, garageSpaces: null, daysOnMarket: null, waterfront: false, views: false, newConstruction: false, openHouse: null, agentLAG: '65120', agentName: 'Stephen Macdonald', mapX: 24, mapY: 12, taxesAnnual: null, description: 'A 3-bedroom, 2-bath home in Bothell, WA, offered through NWMLS and Compass.', features: ['Provided by NWMLS, Compass'] }
];

// Each pin position (mapX/mapY) is a placeholder percentage for visual
// design only — NOT a real coordinate. Replace with lat/lng from the
// IDX feed and a real map provider in PropertyMapSearch.dc.html.
